v*:
  tag_push:
    - stages:
        - name: Create CNB Release
          type: git:release
          options:
            latest: true
            descriptionFromFile: ETS2LA/ReleaseNotes.md
      git:
        submodules: false