<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETS2LA.Logging\ETS2LA.Logging.csproj" />
    <ProjectReference Include="..\ETS2LA.Translations\ETS2LA.Translations.csproj" />
  </ItemGroup>
</Project>
