name: Feature Request
description: Request a feature to be added to the app.
title: "[Feature Request]: "
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out this form to suggest a feature to be added
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature that you want added, what would it do, how would it work?
      placeholder: Description
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you will create a public issue on the ETS2 Lane Assist GitHub page.
      options:
        - label: I understand that I am making a public GitHub Issue
          required: true
