<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="4.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETS2LA.Backend\ETS2LA.Backend.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="ETS2LA.Frontend/dist/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="BuildSvelteApp" BeforeTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Message Text="Building Svelte frontend with Bun..." Importance="high" />
    <Exec WorkingDirectory="ETS2LA.Frontend" Command="bun install" />
    <Exec WorkingDirectory="ETS2LA.Frontend" Command="bun run build" />
  </Target>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Unix'">
    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
  </PropertyGroup>

</Project>
