<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Localization" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Localization\*.po">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.po" />
  </ItemGroup>

  <Target Name="ExtractGetTextStrings" BeforeTargets="BeforeBuild">
    <MakeDir Directories="$(SolutionDir)ETS2LA.Translations/Localization" />
    <Exec Command="dotnet GetText.Extractor -s . -t ETS2LA.Translations/Localization/messages.pot -as _ -ap _n -u" 
          WorkingDirectory="$(SolutionDir)" />
  </Target>
</Project>
