name: Deploy to Releases
permissions:
  contents: write
on:
  push:
    branches:
      - rewrite

jobs:
  pack-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' ETS2LA/ETS2LA.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Install .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: |
          # Build all projects (plugins will not be included in the final package otherwise)
          dotnet build ./ETS2LA.sln -c Release
          # Publish ETS2LA.UI
          .\publish.bat

      - name: Install vpk tool
        run: dotnet tool install -g vpk

      - name: Pack & Upload Velopack
        shell: pwsh
        run: |
          $vpk = Join-Path $env:USERPROFILE '.dotnet\tools\vpk.exe'
          & $vpk pack -u ETS2LA -v ${{ steps.get-version.outputs.version }} -p publish
          & $vpk upload github --channel "win-beta" --pre --merge --repoUrl "https://github.com/${{ github.repository }}" --publish --releaseName "ETS2LA C# v${{ steps.get-version.outputs.version }}" --tag "v${{ steps.get-version.outputs.version }}" --token ${{ secrets.GITHUB_TOKEN }} --targetCommitish ${{ github.sha }}

  pack-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Version from Project File
        id: get-version-linux
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' ETS2LA/ETS2LA.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Install .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: |
          # Linux has it's own .sh script
          dotnet build ./ETS2LA.Linux.slnf -c Release
          ./publish.sh

      - name: Install vpk tool
        run: dotnet tool install -g vpk

      - name: Pack & Upload Velopack
        shell: bash
        run: |
          VPK="$HOME/.dotnet/tools/vpk"
          $VPK pack -u ETS2LA -v ${{ steps.get-version-linux.outputs.version }} -p publish
          $VPK upload github --channel "linux-beta" --pre --merge --repoUrl "https://github.com/${{ github.repository }}" --publish --releaseName "ETS2LA C# (Linux) v${{ steps.get-version-linux.outputs.version }}" --tag "v${{ steps.get-version-linux.outputs.version }}" --token ${{ secrets.GITHUB_TOKEN }} --targetCommitish ${{ github.sha }}