name: Python Workflow

on:
  push:
    branches:
      - main
      - experimental
      # Add more branches as needed

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5  # Set the maximum execution time in minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        foreach ($requirement in Get-Content requirements.txt) {
          $requirements = $requirement -split ' '
          foreach ($singleRequirement in $requirements) {
            if ($singleRequirement -eq "--upgrade" -or $singleRequirement -eq "--no-cache-dir") {
              continue
            }
            Write-Output "Installing $singleRequirement..."
            try {
              python -m pip install $singleRequirement
            } catch {
              Write-Output "Failed to install $singleRequirement. Skipping..."
              continue
            }
          }
        }




    - name: Run main.py
      run: python main.py
