name: Python Workflow

on:
  push:
    branches:
      - main
      - experimental
      # Add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        for requirement in $(cat requirements.txt); do
          if [[ "$requirement" == "--upgrade" || "$requirement" == "--no-cache-dir" ]]; then
            continue
          fi
          if [[ "$requirement" == "--upgrade --no-cache-dir gdown" ]]; then
            echo "Installing gdown..."
          else
            echo "Installing $requirement..."
          fi
          python -m pip install $requirement
        done

    - name: Syntax check
      run: |
        find . -name "*.py" | xargs pylint

    - name: Run main.py
      run: python main.py
