name: Python Workflow

on:
  push:
    branches:
      - main
      - experimental
      # Add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Conditionally run steps based on branch
      run: |
        if [ "$GITHUB_REF" == "refs/heads/main" ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        elif [ "$GITHUB_REF" == "refs/heads/development" ]; then
          # Additional steps for the development branch if needed
        fi

    - name: Syntax check
      run: |
        find . -name "*.py" | xargs pylint

    - name: Run main.py
      run: python main.py
