name: Python Workflow

on:
  pull_request:
    branches:
      - main
      - experimental
      # Add more branches as needed

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5  # Set the maximum execution time in minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        foreach ($requirement in Get-Content requirements.txt) {
          $requirements = $requirement -split ' '
          foreach ($singleRequirement in $requirements) {
            if ($singleRequirement -eq "--upgrade" -or $singleRequirement -eq "--no-cache-dir") {
              continue
            }
            Write-Output "Installing $singleRequirement..."
            try {
              python -m pip install $singleRequirement
            } catch {
              Write-Output "Failed to install $singleRequirement. Skipping..."
              continue
            }
          }
        }



    - name: Run main.py with timeout
      run: |
        Start-Process -FilePath "python" -ArgumentList "main.py" -PassThru -Wait -NoNewWindow | ForEach-Object {
          $_.WaitForExit((15 * 1000))  # 15 seconds timeout
          if (-not $_.HasExited) {
            Write-Output "Terminating the process after 15 seconds."
            $_.Kill()
          }
        }

    - name: Report syntax check status
      uses: actions/github-script@v5
      with:
        script: |
          const status = process.env['CHECK_STATUS'];
          const { data } = await github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'Syntax Check',
            head_sha: context.sha,
            status: status === 'success' ? 'completed' : 'completed',
            conclusion: status,
            output: {
              title: 'Syntax Check',
              summary: status === 'success' ? 'Syntax check passed.' : 'Syntax check failed.',
            },
          });
          console.log('Check run created:', data);

    - name: Set check status
      if: steps.syntax-check.outputs.check_status == 'success'
      run: |
        echo "Check passed!"
