name: Python Workflow

on:
  push:
    branches:
      - main
      - experimental
      # Add more branches as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        Get-Content requirements.txt | ForEach-Object {
          $requirement = $_.Trim()
          if ($requirement -eq "--upgrade" -or $requirement -eq "--no-cache-dir") {
            return
          }
          if ($requirement -eq "--upgrade --no-cache-dir gdown") {
            Write-Output "Installing gdown..."
          } else {
            Write-Output "Installing $requirement..."
          }
          if (-not (python -m pip install $requirement)) {
            Write-Output "Failed to install $requirement. Skipping..."
          }
        }


    - name: Syntax check
      run: |
        Get-ChildItem -Recurse -Filter *.py | ForEach-Object { pylint $_.FullName }

    - name: Run main.py
      run: python main.py
