name: Remove Empty Lines

on:
  push:
    branches:
      - main

jobs:
  remove-empty-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Remove empty lines
      run: |
        # Specify the file you want to check and modify
        FILE_TO_CHECK="requirements.txt"

        # Check if the file contains empty lines
        if grep -q '^$' "$FILE_TO_CHECK"; then
          echo "File contains empty lines. Removing them..."
          # Remove empty lines and overwrite the file
          sed -i '/^$/d' "$FILE_TO_CHECK"
          echo "Empty lines removed."
          git add "$FILE_TO_CHECK"
          git commit -m "Remove empty lines from $FILE_TO_CHECK" || echo "No changes to commit"
        else
          echo "File does not contain empty lines."
        fi
      # Make sure changes are pushed back to the repository
      - name: Push changes
        run: git push
