name: Python Workflow

on:
  push:
    branches:
      - main
      - experimental
      # Add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Conditionally run steps based on branch
      run: |
        case $GITHUB_REF in
          refs/heads/main)
            python -m pip install -r requirements.txt
            ;;
          refs/heads/development)
            # Additional steps for the development branch if needed
            ;;
        esac

    - name: Syntax check
      run: |
        find . -name "*.py" | xargs pylint

    - name: Run main.py
      run: python main.py
